# aws_region         = "us-east-1"
# environment        = "dev"
# vpc_cidr           = "10.0.0.0/16"
# availability_zones = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.10.0/24", "10.0.11.0/24"]
allowed_ssh_ips    = ["x.x.x.x/32"] # Replace with your IP/ List of IPs in format "[x.x.x.x/32]"
key_name           = "Key-Pair-Name"   # Replace with your key pair name
bastion_instance_type = "t2.micro" #Replace with your instance type